version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mysql
    restart: always
    volumes:
      - /Volumes/Emby/Nextcloud/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= nextcloud
      - MYSQL_PASSWORD= nextcloud
      - MYSQL_DATABASE= nextcloud
      - MYSQL_USER= nextcloud
    ports:
      - 9372:5432

  app:
    image: nextcloud
    restart: always
    ports:
      - 9370:80
    links:
      - db
    volumes:
      - /Volumes/Emby/Nextcloud/var/www/html
    environment:
      - MYSQL_PASSWORD= nextcloud
      - MYSQL_DATABASE= nextcloud
      - MYSQL_USER= nextcloud
      - MYSQL_HOST= db
